### ISSUE TITLE
Xcode Unit Test step fails without any error, with exit code 65

### ISSUE THREAD

**Issue by tsabend** [bitrise-io/bitrise.io#5] opened 2015-04-24 19:43 UTC
We've been unable to get any of our builds to pass.

This might have something to do with Xcode 6.3?

**Comment by viktorbenei** [comment] 2015-04-24 19:53
Additional notes from the logs we received from the two teams who reported the issue:

* Happens for `xcodebuild ... clean test` action
* last Xcode log lines: `/usr/bin/touch -c ...` and then `** TEST FAILED **`
* Xcode does not provide any `error:` in the logs, just returns an exit code 65

There are a couple of `warning:` lines in both cases, but there's just two which is present in both logs:

* `ld: warning: directory not found for option` with a path pointing **inside** the git repository
* a variation of `warning: will never be executed` (not exactly the same)

**Comment by viktorbenei** [comment] 2015-04-27 16:41
One of the teams reported that this solution works:

    #!/bin/bash
    xcodebuild -verbose -workspace "X.xcworkspace" -scheme "X" -destination "platform=iOS Simulator,name=iPhone 6 Plus,OS=8.3" test
    sleep 10
    xcodebuild -verbose -workspace "X.xcworkspace" -scheme "X" -destination "platform=iOS Simulator,name=iPhone 6,OS=8.3” test

**Comment by viktorbenei** [comment] 2015-06-17 10:20
Is this still an active issue? Even with the latest virtual machine which includes Xcode 6.3.2?

**Comment by tsabend** [comment] 2015-06-18 13:32
Issue has been resolved, thanks!

**Comment by viktorbenei** [comment] 2015-06-18 13:56
@tsabend If you have time: was it fixed by the upgrade of Xcode, or with a custom solution on your side?

**Comment by tsabend** [comment] 2015-06-18 14:00
The upgrade fixed it.

**Comment by viktorbenei** [comment] 2015-06-18 14:03
Thanks!

**Comment by viktorbenei** [comment] 2015-07-28 15:52
This same issue was reported again - reopening it..

**Comment by adcooley** [comment] 2015-07-28 15:56
they started failing for us on july 26th. I can't reproduce with xcodebuild on my laptop.

**Comment by singhamit089** [comment] 2015-09-14 17:27
I have facing the same issue, unable to reproduce it locally but on bitrise it fails, any solution yet ?

**Comment by viktorbenei** [comment] 2015-09-14 17:55
@singhamit089 thanks for reporting! Could you please send us your logs in email? It would help a lot! 

For a quick fix you can use the solution mentioned above.

**Comment by singhamit089** [comment] 2015-09-14 19:53
@viktorbenei for now, I have deleted the MyApp-Test -> Build Setting -> Testing -> Test Host and its working fine, there was  $(BUILT_PRODUCTS_DIR)/MyApp.app/MyApp earlier and turns out nothing of that sort existing in that particular location and that is why test failed were caused on bitrise. Still no answer for why the test were successfully locally.

**Comment by viktorbenei** [comment] 2015-09-14 20:00
Thanks @singhamit089 - so it was actually an Xcode project settings. It's certainly an interesting issue, as Xcode does not report any error (as noted here https://github.com/bitrise-io/bitrise.io/issues/5#issuecomment-96045769), which makes it a "bit" hard to solve it..

Again, thanks for reporting, it's good to know that Xcode project settings can cause an issue like this! It's still not clear why Xcode does not provide any errors in a case like this..

**Comment by tomaskraina** [comment] 2015-09-15 11:47
I'm having the very same issue at the moment. Moreover, I've found this line buried in the middle of the log:

```
2015-09-15 04:34:02.633 xcodebuild[964:4881]  iPhoneSimulator: Timed out waiting 120 seconds for simulator to boot, current state is 1.
```

Any idea how to fix it?

**Comment by singhamit089** [comment] 2015-09-15 12:27
@tomaskraina did you try the solution I have mentioned ? What is the test host in the testing section ?

**Comment by tomaskraina** [comment] 2015-09-15 12:34
@singhamit089 hmm, I double checked and found out that the host was still set in the test target... trying again.

**Comment by viktorbenei** [comment] 2015-09-15 12:37
@tomaskraina this is not related to this issue, I created a separate one at the related Step: https://github.com/bitrise-io/steps-xcode-test/issues/4 - please Subscribe to that issue if you want to be notified when the new Xcode Test step is released!

**Comment by viktorbenei** [comment] 2015-09-28 14:07
Great news for everyone still interested/affected! We believe we just found the bug what caused this and a fully working "workaround" is now included in the latest `xcode-test` step (version 1.4.0)!

In brief: if you run `xcodebuild ... test` the compilation time is actually **added to the boot time**, which means that if the project compiles for a very long time it might cause a "boot timeout"! This was verified with this sample project, and there's a related Apple Radar ticket as well: https://github.com/bitrise-io/simulator-launch-timeout-includes-build-time

The solution in short: if you include the `build` verb/command **before** the `test` the compilation will happen separately, and so it won't affect the simulator boot time. The fix was as easy as: `xcodebuild ... build test ...` instead of just `xcodebuild ... test ...`.

I'll close this ticket once again as so far it fixed this issue in 100% of our tests, but feel free to reopen/report again if you would still experience the timeout with the latest `xcode-test` (v1.4.0) step!

**Closed by viktorbenei** 2015-09-28 14:07 UTC
Labels: bug

**Comment by amol-c** [comment] 2015-09-30 21:17
So, changing ```xcodebuild ... test ...``` to ```xcodebuild ... build test ...``` didn't work for me.

I ended up doing the following.

```
set -o pipefail && xcodebuild -verbose -workspace tpt-ios.xcworkspace -scheme tpt-ios -sdk iphonesimulator9.0 -destination 'platform=iOS Simulator,name=iPhone 6 Plus,OS=9.0' build test | xcpretty -c
sleep 10
set -o pipefail && xcodebuild -verbose -workspace tpt-ios.xcworkspace -scheme tpt-ios -sdk iphonesimulator9.0 -destination 'platform=iOS Simulator,name=iPhone 6 Plus,OS=9.0' test | xcpretty -c
```

**Comment by viktorbenei** [comment] 2015-09-30 21:18
what was the error @amol-c ? can you send us the logs?

**Comment by amol-c** [comment] 2015-09-30 21:24
The error was just an abrupt failure when running the test using xcodebuild

```** TEST FAILED **```
Also, i came across
```Timed out waiting 120 seconds for simulator to boot, current state is 1.```

But, i am not using Bitrise.io. I was just using plain old xcodebuild on travis. It might not be related to `bitrise`, but i ended up spending entire day figuring out what was going wrong before i stumbled onto this thread.

Let me know, if you still want to take a look at the log.

**Comment by viktorbenei** [comment] 2015-09-30 21:30
I think that error is not related to the original one reported here, but in anyway the `Timed out waiting 120 seconds for simulator to boot, current state is 1.` error seems to be fixed in our case by calling `xcodebuild` directly with `xcodebuild ... build test ...` instead of `xcodebuild ... test ...`.

There was an SSH related issue which resulted in an error like this (120 sec timeout), but it was fixed at travis as well AFAIK. Other than that we only saw this boot timeout in case it actually takes more than 120 seconds to boot the simulator, and in the if `build` is not passed to `xcodebuild`, as in that case the compilation time is added to the "boot" time.

So far this issue seems to be fixed on our platform ( bitrise.io ).

**Comment by viktorbenei** [comment] 2015-09-30 21:33
@amol-c can it be, that `xcpretty` somehow slows down the process in your case? I can't really think about anything else what would cause

```
set -o pipefail && xcodebuild -verbose -workspace tpt-ios.xcworkspace -scheme tpt-ios -sdk iphonesimulator9.0 -destination 'platform=iOS Simulator,name=iPhone 6 Plus,OS=9.0' build test | xcpretty -c
```

to fail, but not

```
set -o pipefail && xcodebuild -verbose -workspace tpt-ios.xcworkspace -scheme tpt-ios -sdk iphonesimulator9.0 -destination 'platform=iOS Simulator,name=iPhone 6 Plus,OS=9.0' build test | xcpretty -c
sleep 10
set -o pipefail && xcodebuild -verbose -workspace tpt-ios.xcworkspace -scheme tpt-ios -sdk iphonesimulator9.0 -destination 'platform=iOS Simulator,name=iPhone 6 Plus,OS=9.0' test | xcpretty -c
```

**Comment by amol-c** [comment] 2015-09-30 21:48
Technically, i cannot use `xcodebuild` directly on travis because of being verbose (even after taking out the keyword `-verbose`), because of the 4MB log limit which gets exceeded easily. I could write it to a file and check it out and get back to you.

Thanks.

**Comment by ishaq** [comment] 2015-11-27 16:34
I just faced this, Turning "Generate Code Coverage Files" in the workflow editor OFF (or setting it to `no` in bitrise.yml when testing locally) fixed it.

**Comment by viktorbenei** [comment] 2015-12-04 07:31
We saw the original issue ( https://github.com/bitrise-io/bitrise.io/issues/5#issuecomment-96045769 ) happen for an OS X project as well. In that case the issue was most likely that the project required a newer OS X version (as the minimum deployment target) than the OS X version the build was running on. Most likely, because the project can't be modified to use anything older than OS X 10.11 (El Cap).

**Comment by viktorbenei** [comment] 2015-12-05 13:15
One more note: it seems that if you use `xcpretty` you'll get a similar issue (that you don't get any error just the exit code 65) in cases where the `xcodebuild` output might include the error. One case is `signal: segmentation fault` - it seems that if the output is piped through `xcpretty` this error is simply not presented, only `exit status 65` is. This issue is **not** related to the original one discussed here, as `segmentation fault` is a random issue, the next build with the exact same configuration will most likely be successful; the original issue results in a constant error, where if you run it again with the same configuration you get the same output, the one described here: https://github.com/bitrise-io/bitrise.io/issues/5#issuecomment-96045769

**Comment by ishaq** [comment] 2016-01-21 10:49
Here's another finding, if your unit tests raise an exception e.g. you try to force unwrap an optional that's nil, you'll get only `exit code 65`. If you run the tests through Xcode, you'll probably get better reporting.

The point being, don't assume it's necessarily a bug that has triggered `exit code 65`, it could be an incorrectly written test as well. (in my case, Unit Test called a function that did not expect to be find a nil in product app, but did find a nil in Unit Tests. It started giving us exit code 65).

This can be a real pain if you have `continueAfterFailure` set to `true` (it's set to `true` by default for Unit Tests) because it would make the following test fail with exit code 65.

```
func testExample() {
    let vc: UIViewController? = nil
    XCTAssertNotNil(vc) // this assertion will fail, but since continueAfterFailure is true, it will not stop here
    let vc2: UIViewController = vc! // here we force unwrap `vc`, it is nil, so we get `exit code 65`
}
```

**Comment by viktorbenei** [comment] 2016-01-21 11:21
Does the error show up in "raw" output mode? Do you have a suggestion how this could be solved / what should be changed in the Step? @ishaq

**Comment by ishaq** [comment] 2016-01-21 11:40
@viktorbenei it shows up as `exit code 65` in raw (xcodebuild) output as well. I believe this is an issue in xcodebuild, so probably not something that can be easily worked around by you guys. In Xcode, I had breakpoints enabled on exceptions so I was able to catch it when it hit the breakpoint.

**Comment by viktorbenei** [comment] 2016-01-21 11:52
@ishaq  You're probably right.. If you'd come up with an idea for a fix/change for the Xcode Test step please let us know!

**Comment by ishaq** [comment] 2016-01-21 12:08
apple should report it as ___unexpected failure___ in the corresponding test. Lets hope they implement that

**Comment by zackshapiro** [comment] 2016-02-29 00:42
I believe I'm experiencing it as well. Any solution?

![http://cl.ly/0R0S1V3o1s2C/Screen%20Shot%202016-02-28%20at%207.42.31%20PM.png]()

**Comment by viktorbenei** [comment] 2016-02-29 09:12
@zackshapiro this is a completely different problem.

`'/storefront.xcworkspace' does not exist.` -> it means that you specified the `.xcworkspace` path incorrectly; most likely you wanted to set it to `./storefront.xcworkspace` instead of `/storefront.xcworkspace`, as the second one is an **absolute** path, while the first one (`./`) is a **relative** path.

**Comment by rad3ks** [comment] 2016-02-29 11:22
I had similar issue `exit code 65`, but the cause was really nasty multithreading issue in the app, what made tests crash with this error. I suggest you guys to check if that's not an issue. Also I suggest to use `xcodebuild` instead of `xcpretty` so you can see in details what's going on, just to fix the problem.

**Comment by SamGJohn** [comment] 2017-05-08 22:24
here's a fix for [xcodebuild exit code 65](https://circleci.com/blog/xcodebuild-exit-code-65-what-it-is-and-how-to-solve-for-ios-and-macos-builds/)

**Comment by viktorbenei** [comment] 2017-05-09 10:50
@SamGJohn no, that's not a fix. Exit code 65 means "something during the build failed". Other than that, it can be **anything**, including: syntax error somewhere, any build or compile error, code signing error, ...

Our Xcode Test step includes common workarounds for timeouts etc. so usually exit code 65 is related to code signing or compile/build issues.

**Comment by viktorbenei** [comment] 2017-05-09 10:53
Of course if you run xcodebuild commands yourself then indeed 65 can be related to simulator timeout, but if you use our **Xcode Test** step, that includes the workaround you linked.
