### ISSUE TITLE
iOS build "corrupts" assets

### ISSUE THREAD

**Issue by DeFrenZ** [bitrise-io/bitrise.io#33] opened 2016-03-02 10:42 UTC
I know it's a strange issue and that it might look like it's more of my fault than yours, but bare with me for a moment.

Context:
Use my Bitrise workflow which builds from branch and then uploads to S3
The build is there and fine, but crashes on a certain point (the crash is happening exactly when ensuring the presence of a resource, to be specific an image)
If I do the build myself it's fine
Also doing the same process the workflow does from CLI doesn't give that issue

Tried both on simulator and device, both built from Xcode or `xcodebuild`, both installed manually or from the same S3 address the workflow would upload to.

I want to say that it's not an issue with the code (even though I can't be 100% sure of course) but I don't know where the issue could be your part either. I'm at a loss but since this happens only through the workflow I think that there's something amiss here.

Can give any amount of details if requested :)

**Comment by viktorbenei** [comment] 2016-03-02 10:45
Could you please send us the build log in email? https://www.bitrise.io/contact

And in general: this can be something as simple as: you have a PNG image with a .jpg extension or anything similar where Xcode sometimes can't process the file in the expected way.

You can also check this guide about possible differences & solutions if something works on your Mac but not on bitrise.io : http://devcenter.bitrise.io/docs/build-error-ld-file-not-found

**Comment by DeFrenZ** [comment] 2016-03-02 10:50
Unluckily I have to say that, while that link is helpful, it's not in this case: Tried clean builds (cleaning Derived Data as well), no duplicate schemes and no CocoaPods...

I know about that issue with images, and I know also that you can find a similar issue between simulator and device due to the different case-sensitivity of the OSes... and that's why I specified it works on both with local builds :)

I used the full log (without `xcpretty`) to inspect the log as well and didn't find anything useful, but I'll send it to you via email now as requested :)

**Comment by viktorbenei** [comment] 2016-03-02 10:53
By "corrupts" assets you mean something's missing from the IPA? Did you validate this by extracting / checking the IPA? Could you please share a bit more about how/where the issue happens (e.g. app crashed on a physical iOS device)?

**Comment by DeFrenZ** [comment] 2016-03-02 11:12
By "corrupt" I mean that it's not found by the iOS API.
The IPA is validated successfully at build time, and while I didn't extract it (it's in the `Assets.car` file) I know that the catalog gets bundled because other resources from it work correctly.
I know for sure that other resources from the catalog get loaded correctly, checking now if other resources from the same `.xcassets` file do as well.
What happens is that the app crashes because it does `UIImage(named:)!`, so when it doesn't find the resource (returns `nil`) the unwrapping causes it.
But the resource gets found correctly on local builds on all architectures...

**Comment by viktorbenei** [comment] 2016-03-02 11:21
Our best guess right now is that you, somehow, do have this file on your Mac, but it's not stored in your repository (e.g. you drag-and-dropped the file from somewhere on your Mac as a "reference" type, and the file is outside of the repository).

It's hard to say without the code, it can also be that the resource is in a sub-module / stored somewhere else (in another repo) which is available on your Mac but not on bitrise.io

The best to check this would be to `git clone` the repository on a new Mac / OS X VM and see if the file's actually there.

Another option would be to check the file on bitrise.io during the build: you can add a Script step to the workflow with a content like:

```
#!/bin/bash
set -x

ls -alh ./path/to/the/missing/file/dir
```

To list the directory content of where the missing file supposed to be. You should run this before the Xcode Archive step and/or right after that.

**Comment by DeFrenZ** [comment] 2016-03-02 11:45
I can confirm that other assets in the same `.xcasset` get found in the CI build.
Also these files are all in the repo, and just made a colleague clone the repo and the "missing" assets are there.

I can try to add some logs in the code that I will check on the CI build but no good idea to what to log exactly :\

**Comment by viktorbenei** [comment] 2016-03-02 12:00
The thing is, if you check the related step(s) source code, all of our Xcode test steps use `xcodebuild` directly, without any hacks. We don't move files in the steps, it's all up to `xcodebuild`.

Can this be an Xcode version difference? Do you build with Xcode 7.2.1 (current default on bitrise.io) locally?

One more thing: can you please try to run the bitrise.yml with our [CLI](https://www.bitrise.io/cli) on your Mac? You can copy-paste the `bitrise.yml` from the workflow editor on bitrise.io and just save it as `bitrise.yml` into your repository root, and run it with bitrise CLI: `bitrise run primary` (if your workflow is called `primary`, which is the default when you register an app on bitrise.io).

**Comment by viktorbenei** [comment] 2016-03-02 12:03
If it works with the CLI on your Mac it means that the issue is not related to any step but to the environment - which can be a tool version difference, cache, or something else.

> Also these files are all in the repo, and just made a colleague clone the repo and the "missing" assets are there.

Did you check what happens if you Archive the project on that Mac? Are the assets compiled into the IPA there?

**Comment by DeFrenZ** [comment] 2016-03-02 13:11
I managed to reproduce the issue by using bitrise CLI on a fresh cloned repo.
I will tackle it somehow from here...

Thanks for the assistance!
(will drop here the solution hopefully just for reference)

**Comment by viktorbenei** [comment] 2016-03-02 13:25
Thanks, and if you can find anything what can be related to a Step (most likely to the Archive step) please let us know, we'll fix it ASAP!

Thanks again for your time and for reporting!

**Comment by DeFrenZ** [comment] 2016-03-02 13:29
Ok, I figured out everything now.
It was a case issue indeed even though I checked it.

And the reason was... that git doesn't care for case differences on diffs so that didn't get committed... and the cloned repo had the differently cased resource, causing the API to not find the image.

Thanks again :)

(the only thing about the step is that `xcpretty` might eat the "compile assets" message, apart from that nothing much to say really :) )

**Comment by viktorbenei** [comment] 2016-03-02 14:34
Ouch, and indeed you're right, we had issues with commits where we only changed capitalization of the file name, and then the file appeared in it's new and old form across our team..

That was the time we learned to **never** do this again, and change *something* else too in the file, or use an intermediate file name before switching the capitalization.. It was a painful lesson on our part - hopefully you didn't waste as much time as we did 😜

Anyway, thanks for reporting the solution, I guess this'll be useful for other too in the future!

I'll close this ticket now, but if you have anything else related to the ticket feel free to comment, and if required we'll re-open it.

**Closed by viktorbenei** 2016-03-02 14:34 UTC
